### ISSUE TITLE
McAfee reports 'BehavesLike.Win32.Generic.tc' when downloading Windows release package

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailPythonIndexer#48] opened 2019-07-30 09:11 UTC

**Comment by mlangkabel** [comment] 2019-08-12 15:09
This seems to be a false positive caused by Pyinstaller which is used to freeze the SourcetrailPythonIndexer package: https://www.virustotal.com/gui/file/471bc7ccd2c231d8d7c3105108defa5f79daee69242be27ceb02569228a5dceb/detection

**Comment by mlangkabel** [comment] 2019-08-26 10:27
Fixed with merge of pull request #51 by using a self-built version of the pyinstaller bootloader as suggested by [this stackoverflow answer](https://stackoverflow.com/a/52054580/2797295).

**Closed by mlangkabel** 2019-08-26 10:27 UTC
Labels: bug
